const HeaderMarquee = [
  "Art is not what you see, but what you make others see.",
  "•",
  "#ArtToday",
  "•",
  "Every wall is a canvas, every silence is a story.",
  "#StreetVoices",
  "•",
  "Beauty doesn’t ask for attention it whispers.",
  "#UrbanPoetry",
  "•",
  "Create, not to impress, but to express.",
  "#MoreThanWords",
  "•",
  "Nothing is ever finished.Everything evolves.",
  "#MinimalThoughts",
  "•",
  "See the unseen. Feel the unspoken.",
];

const FooterMarquee = [
  "'Don’t Close Your Eyes' — new magazine piece by Jakob Grønberg",
  "•",
  "'The Art of Movement' — listen to the latest podcast",
  "•",
  "'Street Art Festival: Where the Walls Speak' — new article",
  "•",
  "'Hope Dies Last' — a reflection by Louise Jensen",
  "•",
  "'The Hidden Messages of Jack Nielson' — discover the unseen layers",
  "•",
  "'Getting Real' — truth behind the filters by Anna Nielsen",
  "•",
  "See beyond the surface – Read, listen, reflect.",
  "•",
  "This is where art breathes. This is where stories live.",
  "•",
  "Words that move. Sounds that resonate. Art that lingers.",
  "•",
  "Not just articles. Not just podcasts. Conversations.",
  "•",
  "A digital garden of culture, curated with care.",
  "•",
  "We don’t follow trends. We follow meaning.",
  "•",
];

export { FooterMarquee, HeaderMarquee };
